package de.thm.smarthome.global.enumeration;

/**
 * Created by Nils on 15.04.2017.
 */
public enum EUnitOfMeasurement {
    NA,
    TEMPERATURE_DEGREESCELSIUS,
    TEMPERATURE_DEGREESFAHRENHEIT,
    VELOCITY_KILOMETERSPERHOUR,
    VELOCITY_MILESPERHOUR,
    VOLUME_LITRESPERSQUAREMETER,
    VOLUME_GALLONSPERSQUAREINCH,
    PRESSURE_BAR,
    PRESSURE_POUNDFORCEPERSQUAREINCH,
    DISTANCE_METERS,
    DISTANCE_FEET,
    RELATION_PERCENT
}
